### ISSUE TITLE
[question] Is it possible to force the polyfill over native shadowDom?

### ISSUE THREAD

**Issue by jorrete** [skatejs/named-slots#106]
My case. I'm preparing a set of wc using shadowDom. I am using regex to "port" styles using :host, ::slotted, etc.. to the _shadow_root_.  Everything works well, chrome (native), firefox, edge, and safari, but with safari (preview and nightly) I'm getting problems with "display: flex" on de wc. It seems that doesn't work.
So, my fear  is to use the polyfill and feel that  everything seems to work properly. But suddenly  the native shadowDom it is activated on Safari and because bugs, or different implementantion of the specs, problems would arise.
My question is if it would be possible to force the polyfill over native so I can control when to switch to native implementation.

Thanks!!

**Comment by treshugart** [comment]
Hey @jorrete I totally didn't see this, sorry. I was thinking about this the other day because, ideally, you'd only load the polyfill in browsers that _don't_ support native, but that's hard for some, so it'd be nice to switch it on at will while always loading it (not ideal, but practical for some). 

I've also had problems with Safari, but mine might be a little different. See https://bugs.webkit.org/show_bug.cgi?id=160331.

I think this is doable, but it's not really the standard way polyfills normally behave which might catch some up. Would it be better to have a separate export that exports a function that does the polyfilling so users, by default, get the polyfill and you can opt-in to importing a function that you can call to enable the polyfill?

**Comment by jorrete** [comment]
That would be perfect for me. I use a custom function to register WC where I attach the shadow DOM and do other stuff. In that case, I could control when to switch to native.
Thanks.

**Comment by treshugart** [comment]
Fixing in https://github.com/skatejs/named-slots/pull/126
