### ISSUE TITLE
Bower Install broken

### ISSUE THREAD

**Issue by ryansolid** [skatejs/named-slots#83]
bower.json sets the entry point to the dist folder. A recent commit added it to the gitignore removing it from the install.

**Comment by joscha** [comment]
that is because we are not checking in the dist folder any more. I think the right way would be to remove the bower.json file altogether as do not want to support bower installs in the future. What do you think @treshugart ?

**Comment by treshugart** [comment]
I would consider this a bug. This would have been an oversight in the updated build package where it has an npm prepublish but that wouldn't work for bower. I think a solution for this would be to publish `dist/` as part of the tag. I haven't automated this yet, but maybe you (@joscha) have?

**Comment by joscha** [comment]
I think the problem is, that the bower install happens from the git repo and we don't commit the dist any more, or no? Can you clarify @ryansolid ?

**Comment by treshugart** [comment]
No we don't. Standard practice in that case would be to somehow commit it
to the tag. I just thought you may have done that before. People are crying
for a postinstall hook in bower but I don't think they've done it yet. Last
time I checked (on phone and home with fam so can't check right now) their
claim was that it's an anti pattern.

**Comment by joscha** [comment]
we removed the dist because npm manages the build artifacts for us. No need for endless diffs or conflicting PRs just because the dist is incompatible. I'd hope we can just drop bower support - anyone interested in getting the dist can do so by installing via npm and copying it over?

**Comment by Nevraeka** [comment]
@joscha & @treshugart - many people still use Bower (sadly since support from Twitter has officially dropped). You could have instructions in the README and docs for installing through Bower via git (similar to many Polymer Elements) By this, you wouldn't have to register or publish your packages to Bower. Of course, I would consider unpubllishing or marking existing packages already published to Bower as _deprecated_ (prob better) . So something to the effect of this...

## Install

Installing with [NPM](https://npmjs.org) is easy...

```
$ npm i --save named-slots
```

**_[Bower](https://bower.io) support is limited and our bower packages have been deprecated**_
We recommend installing via NPM or JSPM. In the event you still want to install `named-slots` with Bower, please use their Git API (see below).

```
$ bower install --save skatejs/named-slots
```

**Comment by treshugart** [comment]
Seems bower now supports a postinstall hook. For more info see https://bower.io/docs/config/#bowerrc-specification. All we'd need to do is do what we do in the package.json, in our bower.json. Win.

**Comment by joscha** [comment]
that assumes npm being available though - for a bower env that might not be true?

**Comment by treshugart** [comment]
If they want to use Skate via Bower, maybe we make that part clear?

**Comment by joscha** [comment]
but if there is npm available, why not use it to install in the first place? Then the dist files would be in place as well, hence `bower.json` would work (for whatever reason there is to use bower instead of npm if there is npm). Sorry, I am just a bit confused by this discussion. I see that we broke `bower.json`, but I think we need to either remove it altogether (my recommendation) or publish a working branch/package to bower that contains the dist.

**Comment by treshugart** [comment]
That's true. I guess I'd like to keep bower support if time and effort permit, but I'm not too attached to it. Happy to remove, too. Personally, I've never had a situation where I needed to use Bower where NPM didn't do the job the same or better.

**Comment by ryansolid** [comment]
I see. I get your position. I think npm 3 removes the need for Bower. It hasn't been considered ready enough to ship with Node until version 6 which last I checked isn't LTS yet. Would have liked to see the support last until then, but I can definitely see why an experimental forward thinking polyfill wouldn't prioritize any effort there.
